### model
model_name_or_path: saves/douban/sft_ckpt/

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.5
pref_ftx: 0.0
pref_loss: sigmoid
deepspeed: train_config/ds_z2.config.json
max_grad_norm: 1.0

### dataset
dataset: 
template: qwen
cutoff_len: 768
overwrite_cache: true
preprocessing_num_workers: 8
### output
output_dir: saves/douban/dpo_stage1
save_steps: 20
plot_loss: true
overwrite_output_dir: false
save_total_limit: 10

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
logging_strategy: steps
logging_steps: 3
remove_unused_columns: false
dataloader_num_workers: 8

