### model
model_name_or_path: /mmu_vcg_wjc_hdd/duyong/plms/QWen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
max_grad_norm: 1.0

### dataset
dataset: dataset/train_data/qwen_train.json
template: qwen
cutoff_len: 768
overwrite_cache: true
preprocessing_num_workers: 8
tokenized_path:


### output
output_dir: saves/douban/sft_lora_ckpt
save_steps: 100
plot_loss: true
overwrite_output_dir: false
save_total_limit: 20

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
logging_strategy: steps
logging_steps: 3

